language: node_js
node_js: 
        - "6"
cache:
  directories:
    - node_modules # local npm modules

notifications:
  email: false

os:
  - osx
  - linux

script:
  - npm run test

branches:
  only:
    - master
